### ISSUE TITLE
Hand wheel communication

### ISSUE THREAD

**Issue by austinthetaco** [strawlab/tilta-n2-control#1]
Apologies if this is the wrong place to ask, but do you happen to have any documentation or direction or research for communicating/receiving communication from the nano 2 handwheel? i'd like to build a custom motor for something and control it with the handwheel

**Comment by DeepSOIC** [comment]
https://github.com/strawlab/tilta-n2-control?tab=readme-ov-file#packets-from-the-knob
i think that's most of what you have to know. Receive them, parse them, and you should be on your way to success. 

I have a slight concern that the addresses in these packets change from device to device. We have only one of each so far.

`motor command type` number changes depending on what you're actuating (focus, zoom, aperture)

**Comment by DeepSOIC** [comment]
also i've seen the wheel aggregate commands for different motors into one packet... i think.
